python main_supcon.py --dataset fashion --batch_size 32 --epochs 10 --learning_rate 0.5 --t
emp 0.1 --cosine

Traceback (most recent call last):
  File ".\main_supcon.py", line 304, in <module>
    main()
  File ".\main_supcon.py", line 283, in main
    loss = train(train_loader, model, criterion, optimizer, epoch, opt)
  File ".\main_supcon.py", line 223, in train
    features = model(images)
  File "C:\Users\ibarrien\Anaconda3\envs\TorchEnv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\ibarrien\PycharmProjects\SupervisedConstrastiveLosss\networks\resnet_big.py", line 185, in forward
    feat = self.encoder(x)
  File "C:\Users\ibarrien\Anaconda3\envs\TorchEnv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\ibarrien\PycharmProjects\SupervisedConstrastiveLosss\networks\resnet_big.py", line 117, in forward
    out = F.relu(self.bn1(self.conv1(x)))
  File "C:\Users\ibarrien\Anaconda3\envs\TorchEnv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\ibarrien\Anaconda3\envs\TorchEnv\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\ibarrien\Anaconda3\envs\TorchEnv\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 3-dimensional input of size [2, 28, 28] instead
